/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPublicKeyRegistry } from "./IPublicKeyRegistry";
export type { PublicKeyRegistry } from "./PublicKeyRegistry";
