/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPublicKeyRegistry__factory } from "./IPublicKeyRegistry__factory";
export { PublicKeyRegistry__factory } from "./PublicKeyRegistry__factory";
