/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPublicKeyRegistry,
  IPublicKeyRegistryInterface,
} from "../../../contracts/infra/IPublicKeyRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "providerId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "publicKeyHash",
        type: "bytes32",
      },
    ],
    name: "checkPublicKey",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPublicKeyRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IPublicKeyRegistryInterface {
    return new Interface(_abi) as IPublicKeyRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPublicKeyRegistry {
    return new Contract(address, _abi, runner) as unknown as IPublicKeyRegistry;
  }
}
