/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  JwtVerifier,
  JwtVerifierInterface,
} from "../../contracts/JwtVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract UltraVerifier",
        name: "ultraVerifier_",
        type: "address",
      },
      {
        internalType: "contract PublicKeyRegistry",
        name: "publicKeyRegistry_",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "accountId",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "authProviderId",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "jwtAud",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "publicKeyRegistry",
    outputs: [
      {
        internalType: "contract PublicKeyRegistry",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ultraVerifier",
    outputs: [
      {
        internalType: "contract UltraVerifier",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60c060405234801561001057600080fd5b5060405161035738038061035783398101604081905261002f9161005e565b6001600160a01b039182166080521660a052610098565b6001600160a01b038116811461005b57600080fd5b50565b6000806040838503121561007157600080fd5b825161007c81610046565b602084015190925061008d81610046565b809150509250929050565b60805160a05161029c6100bb600039600060ee015260006071015261029c6000f3fe608060405234801561001057600080fd5b50600436106100675760003560e01c80636b124f5b116100505780636b124f5b146100d257806386aeebf7146100e95780639cfd7cff1461011057600080fd5b8063343e24931461006c5780635ad662d4146100bd575b600080fd5b6100937f000000000000000000000000000000000000000000000000000000000000000081565b60405173ffffffffffffffffffffffffffffffffffffffff90911681526020015b60405180910390f35b6100c5610119565b6040516100b491906101a7565b6100db60025481565b6040519081526020016100b4565b6100937f000000000000000000000000000000000000000000000000000000000000000081565b6100db60005481565b6001805461012690610213565b80601f016020809104026020016040519081016040528092919081815260200182805461015290610213565b801561019f5780601f106101745761010080835404028352916020019161019f565b820191906000526020600020905b81548152906001019060200180831161018257829003601f168201915b505050505081565b602081526000825180602084015260005b818110156101d557602081860181015160408684010152016101b8565b5060006040828501015260407fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe0601f83011684010191505092915050565b600181811c9082168061022757607f821691505b602082108103610260577f4e487b7100000000000000000000000000000000000000000000000000000000600052602260045260246000fd5b5091905056fea26469706673582212208f74073c0fd0ba74fbc56eeb26aa257ba37a3b04997dddf80ba4607ec1954a3a64736f6c634300081b0033";

type JwtVerifierConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: JwtVerifierConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class JwtVerifier__factory extends ContractFactory {
  constructor(...args: JwtVerifierConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    ultraVerifier_: AddressLike,
    publicKeyRegistry_: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(
      ultraVerifier_,
      publicKeyRegistry_,
      overrides || {}
    );
  }
  override deploy(
    ultraVerifier_: AddressLike,
    publicKeyRegistry_: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(
      ultraVerifier_,
      publicKeyRegistry_,
      overrides || {}
    ) as Promise<
      JwtVerifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): JwtVerifier__factory {
    return super.connect(runner) as JwtVerifier__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): JwtVerifierInterface {
    return new Interface(_abi) as JwtVerifierInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): JwtVerifier {
    return new Contract(address, _abi, runner) as unknown as JwtVerifier;
  }
}
